=== nagasaisivasatyasri/day11ass/day18/emptyrealestate.dtd
<!ELEMENT realestate (agencies,owner,properties,flats)*>
<!ELEMENT agencies (aname,email,mob)>
<!ELEMENT owner (oname)>
<!ELEMENT properties (pname,noofflats)>
<!ELEMENT flats (fname,description,rate)>
<!ELEMENT aname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT mob (#PCDATA)>
<!ELEMENT oname (#PCDATA)>
<!ELEMENT pname (#PCDATA)>
<!ELEMENT noofflats (#PCDATA)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT rate (#PCDATA)>

=== nagasaisivasatyasri/day11ass/day18/realestate.xml
<?xml version="1.0" ?>
<!DOCTYPE realestate SYSTEM "emptyrealestate.dtd">
<realestate>
	<agencies>
		<aname>sughandha</aname>
		<email>sughandha@agency.com</email>
		<mob>56566</mob>
	</agencies>
	<owner>
		<oname>saibaba</oname>
	</owner>
	<properties>
		<pname>land</pname>
		<noofflats>5</noofflats>
	</properties>
	<flats>
		<fname>34-90</fname>
		<description>5 cents</description>
		<rate>4000000</rate>
	</flats>
</realestate>
